### PR TITLE
Promise examples

### PR DESCRIPTION
**Pull request by pkozlowski-opensource**
@petebacondarwin Here is the sketch of the examples I had on my mind to explain promises.

Let's discuss code issues here and more general / philosophical issues via e-mail.

Of course not to be merged...

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@petebacondarwin Do you have any comments for 6133a0f? If not I would like to merge it.

**Comment by petebacondarwin** [comment]
Do we ever really use success and error methods in real code?

**Comment by petebacondarwin** [comment]
Good to merge.

**Comment by pkozlowski-opensource** [comment]
Landed as d66dad7e2486c7b07ddfe805ac329d84a418ea94

**Pull request closed without merging**
